# Converting Data Type on Existing Arrays

1. The best way to change data type of on existing array, is to make a copy of the array with the astype() method
2. The astype() function creates a copy of the array and allows you to specify the data type as a parameter
3. The data type can be specified using a string like 'f' for float, 'i' for integer etc. 
4. you can use the data type directly the float

In [1]:
import numpy as np

In [2]:
my_array = np.array([10.10,20.20,30.30,40.50,50.10,30.56])

new_array = my_array.astype('i')

print("After convering array are: ", new_array)

print(new_array.dtype)

After convering array are:  [10 20 30 40 50 30]
int32


In [3]:
my_array = np.array([10.10,20.20,30.30,40.50,50.10,30.56])

new_array = my_array.astype(int)

print("After convering array are: ", new_array)

print(new_array.dtype)

After convering array are:  [10 20 30 40 50 30]
int32


In [5]:
my_array = np.array([10, 20, 30, 40, 50, 30])

new_array = my_array.astype(bool)

print("After convering array are: ", new_array)

print(new_array.dtype)

After convering array are:  [ True  True  True  True  True  True]
bool


In [6]:
my_array = np.array([10.10,20.20,30.30,40.50,50.10,30.56])

new_array = my_array.astype(str)

print("After convering array are: ", new_array)

print(new_array.dtype)

After convering array are:  ['10.1' '20.2' '30.3' '40.5' '50.1' '30.56']
<U32


# Numpy Array Copy vs View

1. The main difference between a copy and view of an array that the copy is new array, and the view is just view of the original array
2. The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy
3. The viw does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view

## 1. Copy

In [7]:
import numpy as np

my_array = np.array([10,20,30,40,50,60])

new_array = my_array.copy()

my_array[0] = 45

print("Old Array: ", my_array)

print("New Array: ", new_array)

Old Array:  [45 20 30 40 50 60]
New Array:  [10 20 30 40 50 60]


In [13]:
import numpy as np

my_array = np.array([10,20,30,40,50,60])
new_array = my_array.copy()

print("Before changes original Array: ", my_array)
print("Before changes View Of Original Array: ", new_array)

new_array[0] = 150

print("After changes original Array: ", my_array)
print("After changes View Of Original Array: ", new_array)

Before changes original Array:  [10 20 30 40 50 60]
Before changes View Of Original Array:  [10 20 30 40 50 60]
After changes original Array:  [10 20 30 40 50 60]
After changes View Of Original Array:  [150  20  30  40  50  60]


**Note : The copy Should Not be affected by the changes made to the original**

# 2. View

In [10]:
import numpy as np

my_array = np.array([10,20,30,40,50,60])

new_array = my_array.view()

# print("Before changes original Array: ", my_array)
# print("Before changes View Of Original Array: ", new_array)

my_array[0] = 89

print("After changes on original Array: ", my_array)
print("After changes View Of Original Array: ", new_array)

After changes on original Array:  [89 20 30 40 50 60]
After changes View Of Original Array:  [89 20 30 40 50 60]


**Note : The view Should be affected by the changes made to the original array**

In [11]:
import numpy as np

my_array = np.array([10,20,30,40,50,60])

new_array = my_array.view()

print("Before changes on View Array: ", new_array)

new_array[0] = 23

print("After changes Original Array",my_array)
print("After changes on View new Array are: ", new_array)

Before changes on View Array:  [10 20 30 40 50 60]
After changes Original Array [23 20 30 40 50 60]
After changes on View new Array are:  [23 20 30 40 50 60]


**Note : The view Should be affected by the changes made to the View Changes**

### Check if Array owns its Data

In [14]:
import numpy as np

my_array = np.array([10,20,30,40,50,60])

x = my_array.copy()
y = my_array.view()

print(x.base)
print(y.base)

None
[10 20 30 40 50 60]


### Numpy Shape of an Array

1. The shape of an arrya is the number of elements in each elements
2. Numpy array have attribute called shape that returns a tuple with each having number of corresponding array

In [15]:
import numpy as np

my_array = np.array([[10,20,30,40],[50,60,70,80]])

my_array.shape

(2, 4)

**which means that 2 dimension, where each dimension has 4 elements**

In [17]:
import numpy as np

my_array = np.array([10,20,30,40,50,60,70,80],ndmin=5)

print(my_array)
print("Shape of Array: ", my_array.shape)

[[[[[10 20 30 40 50 60 70 80]]]]]
Shape of Array:  (1, 1, 1, 1, 8)


# Numpy Array Reshaping

In [18]:
import numpy as np

my_array = np.array([10,20,30,40,50,60,70,80,90,100,110,120])

new_array = my_array.reshape(4,3)
print(new_array)

[[ 10  20  30]
 [ 40  50  60]
 [ 70  80  90]
 [100 110 120]]


In [19]:
import numpy as np

my_array = np.array([10,20,30,40,50,60,70,80,90,100,110,120])

new_array = my_array.reshape(3, 4)
print(new_array)

[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]


In [21]:
import numpy as np

my_array = np.array([10,20,30,40,50,60,70,80,90,100,110,120])

new_array = my_array.reshape(2, 6)
print(new_array)

[[ 10  20  30  40  50  60]
 [ 70  80  90 100 110 120]]


In [24]:
import numpy as np

my_array = np.array([10,20,30,40,50,60,70,80,90,100,110,120])

new_array = my_array.reshape(6, 2)
print(new_array)
print(new_array.ndim)

[[ 10  20]
 [ 30  40]
 [ 50  60]
 [ 70  80]
 [ 90 100]
 [110 120]]
2


In [25]:
import numpy as np

my_array = np.array([10,20,30,40,50,60,70,80,90,100,110,120])

new_array = my_array.reshape(2, 2, 3)
print(new_array)
print(new_array.ndim)

[[[ 10  20  30]
  [ 40  50  60]]

 [[ 70  80  90]
  [100 110 120]]]
3
