# Python Numpy

## 1. What is Numpy ?

1. Numpy is library used for **working with Array**
2. Numpy stands for **Numerical Python**
3. Numpy library consistancy of **multidimensional** arrya object and collection
4. Using Numpy **mathematical and logical operations** on can be performed
5. Numpy also has function working in domain **linear algebra**, **fourier transform** and **matrics**
6. Numpy is open source core Python library for scintific calculation

## Feature of Python

1. High Performance
2. Itegrity code from C and C++
3. Multidimensinal Function
4. Broadcasting Function
5. Worked with Varied Databases
6. Additonal Linear Algebra

#### 1. High Performance [N- Dimensional array object]

1. It is Homogeneous array object
2. Peform all operations an array elements
3. Array in Numpy Unidimensional or One Dimensional or Multidimensional:
    1. Unidimensional Array:
        1. Onle single elements called as Unidimensional array
        2. Example - my_array =[10]
    2. One Dimensinal array:
        1. One dimensional array consisting of single row or single column
        2. Elements of array the homogeneous nature
        3. Example - my_array = [10,20,30,40,50]
    3. Multidimensional array:
        1. We have multiple rows and column
        2. Each column as dimesions, elements, are homogeneous

### 2. Integrating codes from c/c++ and Forton

1. Integrating the functionalities in various programing language this help us to implements inter Platform function

### 3. Multidimensional Container

1. Generic data refers to the parameterized data type of array
2. It can Perform functions on the generic datatype
3. Parameter helps increase the diversity of Array

### 4. Bradcasting Function

1. It is very useful work with Arrya of uneven shape
2. Some rules for limitations and its implementation
3. For broadcasting one array need to be **one dimensional**

### 5. Worked with Varied Database

1. Work with different data types
2. d type function can be used

### 6. Additional Algebra

1. Additional Algebra, Fourier transform, Random Number, capabilities
2. It is ability to perform complex operations of elements like algebra, fourier transform etc.
3. We have separate function for each of complex performs:
    1. Linear Algebra - [ linalg ]
    2. Fourier Transform [ fft]
    3. Matrics - [matrics]
    4. Plotting Graph [ matplotlib ]

## How to Install Numpy ?

1. PIP install Numpy [pip install numpy]
2. Import in applicatio using [import] keyword
3. import numpy [import numpy]
4. using alies [import numpy as np]

### Numpy using alies as np

In [1]:
import numpy as np

In [3]:
# help(np)

In [4]:
my_array = np.array([1,2,3,4,5,6])
print(my_array)

[1 2 3 4 5 6]


In [5]:
print(type(my_array))

<class 'numpy.ndarray'>


## Numpy with alies

In [6]:
import numpy

In [8]:
# help(numpy)

In [9]:
my_array = numpy.array([1,2,3,4,5,6])
print(my_array)

[1 2 3 4 5 6]


In [10]:
print(type(my_array))

<class 'numpy.ndarray'>


### Checking Numpy Version

In [11]:
import numpy as np

1. Version of string stored under [__version__]attributes

In [12]:
print(np.__version__)

1.24.3


### type()

In [13]:
my_array = numpy.array([1,2,3,4,5,6])
print(my_array)
print(type(my_array))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


### Type of Array

1. Numpy is used to work with array
2. The array object in Numpy is called **ndarray**
3. We can create a numpy ndarray object by using **array() function**
4. The built in function in python tell us type of object passed it
5. To creae ndarray we can pas a list, tuple, or any array object into array() method
6. then convert that array to ndarray

In [14]:
my_array = numpy.array(10)
print(my_array)
print(type(my_array))

10
<class 'numpy.ndarray'>


### There are different Types of Array object

1. 0-D Array
2. 1-D Array
3. 2-D Array
4. 3-D Array

### Numpy will devide in to three major categories:
  #### 1. Basic Numpy:
        1. Introduction
        2. Gettting Started
        3. creating Array
        4. Array Indexing
        5. Array slicing
        6. Data Types
        7. Copy vs View
        8. Array Shape
        9. Array Reshape
        10. Array Iterating
        11. Array Join
        12. Array Split
        13. Array search
        14. Array Sort
        15. Array Filter
   ### 2. Random:**
        1. Random Introduction
        2. Data Distribution
        3. Radom Permutation
        4. Seaborn Module
        5. Normal Dist
        6. Binomial Dist
        7. Poisson Dist
        8. Uniform Dist
        9. Logistic Dist
        10. Multinomial Dist
        11. Exposnitial Dist
        12. Chi Square Dist
        13. Rayligh Dist.
   ### 3. ufunct:**
        1. ufunct Introduction
        2. Create function
        3. Simple Arithmatic
        4. Rounding Decimals
        5. Logs
        6. Summation
        7. Products
        8. Differences
        9. Finding LCM
        10. Finding GCD
        11. Trignomatric
        12. Hyperbolic
        13. Set Operations