# Numpy Joining Array

1. Joining means content of two or more arrays in single array
2. In SQl we join table based on a key, whereas in Numpy we join arrays by axis
3. We pass sequence of array that we want to join the concatnate() function along with axis
4. If axis is not explicitly passed if it taken 0

In [1]:
import numpy as np

In [2]:
my_array_1 = np.array([10,20,30,40,50])

my_array_2 = np.array([60,70,80,90,100])

new_array = np.concatenate((my_array_1,my_array_2))

print(new_array)

[ 10  20  30  40  50  60  70  80  90 100]


In [3]:
my_array_1 = np.array([[10,20,30,40],[50,60,70,80]])

my_array_2 = np.array([[90,100,110,120],[130,140,150,160]])

new_array = np.concatenate((my_array_1,my_array_2))

print(new_array)

[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]
 [130 140 150 160]]


In [4]:
my_array_1 = np.array([[10,20,30,40],[50,60,70,80]])

my_array_2 = np.array([[90,100,110,120],[130,140,150,160]])

new_array = np.concatenate((my_array_1,my_array_2), axis =1)

print(new_array)

[[ 10  20  30  40  90 100 110 120]
 [ 50  60  70  80 130 140 150 160]]


## Joining Array using Stack function

In [5]:
my_array_1 = np.array([10,20,30,40,50])

my_array_2 = np.array([60,70,80,90,100])

new_array = np.stack((my_array_1,my_array_2))
print(new_array)

[[ 10  20  30  40  50]
 [ 60  70  80  90 100]]


In [6]:
my_array_1 = np.array([10,20,30,40,50])

my_array_2 = np.array([60,70,80,90,100])

new_array = np.stack((my_array_1,my_array_2),axis = 1)
print(new_array)

[[ 10  60]
 [ 20  70]
 [ 30  80]
 [ 40  90]
 [ 50 100]]


## Stacking with Rows

In [7]:
my_array_1 = np.array([10,20,30,40,50])

my_array_2 = np.array([60,70,80,90,100])

new_array = np.hstack((my_array_1,my_array_2))
print(new_array)

[ 10  20  30  40  50  60  70  80  90 100]


## Stacking with Column

In [8]:
my_array_1 = np.array([10,20,30,40,50])

my_array_2 = np.array([60,70,80,90,100])

new_array = np.vstack((my_array_1,my_array_2))
print(new_array)

[[ 10  20  30  40  50]
 [ 60  70  80  90 100]]


In [9]:
my_array_1 = np.array([10,20,30,40,50])

my_array_2 = np.array([60,70,80,90,100])

new_array = np.dstack((my_array_1,my_array_2))
print(new_array)

[[[ 10  60]
  [ 20  70]
  [ 30  80]
  [ 40  90]
  [ 50 100]]]


## Numpy Splitting Array

1. Splitting is reverse operation of Joining
2. Joining merges multiple arrays into one and splitting break one array to multiple array.
3. We use array_split() for splitting arrays, we pass it in the array we want to split and number of arrays(splits)

In [10]:
my_array_1 = np.array([10,20,30,40,50,60,70,80])

new_array = np.array_split(my_array_1, 3)

print(new_array)

[array([10, 20, 30]), array([40, 50, 60]), array([70, 80])]


In [11]:
my_array_1 = np.array([10,20,30,40,50,60,70,80])

new_array = np.array_split(my_array_1, 4)

print(new_array)

[array([10, 20]), array([30, 40]), array([50, 60]), array([70, 80])]


In [12]:
my_array_1 = np.array([10,20,30,40,50,60,70,80])

new_array = np.array_split(my_array_1, 5)

print(new_array)

[array([10, 20]), array([30, 40]), array([50, 60]), array([70]), array([80])]


In [13]:
my_array_1 = np.array([10,20,30,40,50,60,70,80])

new_array = np.array_split(my_array_1, 3)

print(new_array)

[array([10, 20, 30]), array([40, 50, 60]), array([70, 80])]


In [15]:
print(new_array[1][1])

50


In [16]:
print(new_array[1][:2])

[40 50]


# Splitting 2-D Arrays

1. Use the same syntax while splitting 2-D arryas
2. Use array_split() method pass the array you want to split and number of split

In [17]:
my_array_1 = np.array([[10,20,30,40],[50,60,70,80]])

new_array = np.array_split(my_array_1, 3)
print(new_array)

[array([[10, 20, 30, 40]]), array([[50, 60, 70, 80]]), array([], shape=(0, 4), dtype=int32)]


In [18]:
my_array_1 = np.array([[10,20,30,40],[50,60,70,80]])

new_array = np.array_split(my_array_1, 4)
print(new_array)

[array([[10, 20, 30, 40]]), array([[50, 60, 70, 80]]), array([], shape=(0, 4), dtype=int32), array([], shape=(0, 4), dtype=int32)]


# Numpy Searching Arrays

In [19]:
import numpy as np

In [20]:
my_array_1 = np.array([10,20,30,40,50,60,70,80])

new_array = np.where(my_array_1 == 4)

print(new_array)

(array([], dtype=int64),)


In [21]:
my_array_1 = np.array([10,20,30,40,50,60,70,80])

new_array = np.where(my_array_1 == 40)

print(new_array)

(array([3], dtype=int64),)


In [22]:
my_array_1 = np.array([10,20,30,40,50,60,70,80])

new_array = np.where(my_array_1 % 2 == 0)
print(new_array)

(array([0, 1, 2, 3, 4, 5, 6, 7], dtype=int64),)


In [23]:
my_array_1 = np.array([10,20,31,40,50,61,70,80])

new_array = np.where(my_array_1 % 2 == 0)
print(new_array)

(array([0, 1, 3, 4, 6, 7], dtype=int64),)


In [24]:
my_array_1 = np.array([10,20,31,40,50,61,70,80])

new_array = np.where(my_array_1 % 2 == 1)
print(new_array)

(array([2, 5], dtype=int64),)


# Numpy Array Sorting

In [25]:
my_array_1 = np.array([100,2,31,45,5,61,7,85])

new_array = np.sort(my_array_1)
print(new_array)

[  2   5   7  31  45  61  85 100]


In [26]:
my_array_1 = np.array(['banana','apple','pineapple','mango','cherry','fruit','grapes'])

new_array = np.sort(my_array_1)
print(new_array)

['apple' 'banana' 'cherry' 'fruit' 'grapes' 'mango' 'pineapple']


In [28]:
# help(np.sort(my_array_1))

## Create Filter Array

In [31]:
import numpy as np

my_array_1 = np.array([41,42,43,44,85,70,100])

# create empty list
filter_array = []

output = []

for element in my_array_1:
    if element >= 42:
        filter_array.append(True)
    else:
        filter_array.append(False)
        
new_array = my_array_1[filter_array]

print(new_array)

print(filter_array)


[ 42  43  44  85  70 100]
[False, True, True, True, True, True, True]


In [35]:
import numpy as np

my_array_1 = np.array([41,42,43,44,85,70,100])

# create empty list
filter_array = []

output = []

for element in my_array_1:
    if element >= 42:
        filter_array.append(element)
    else:
        output.append(element)
        
# new_array = my_array_1[filter_array]

print(new_array)

print(output)


[ 42  43  44  85  70 100]
[41]


In [37]:
my_array_1 = [41,42,43,44,85,70,100,41,41,43,44,44,44]

output = {}

for i in my_array_1:
    if i in output:
        output[i] = output[i] + 1
    else:
        output[i] = 1
        
print(output)

{41: 3, 42: 1, 43: 2, 44: 4, 85: 1, 70: 1, 100: 1}


In [38]:
my_array_1 = [41,42,43,44,85,70,100,41,41,43,44,44,44]

output = {}

addtion_op = []

for i in my_array_1:
    if i in output:
        output[i] = output[i] + 1
    else:
        output[i] = 1
        
        
addtion_op.append(sum(output.values()))
        
print(output)
print(addtion_op)

{41: 3, 42: 1, 43: 2, 44: 4, 85: 1, 70: 1, 100: 1}
[13]
