## Numpy Slicing Array

1. Slicing in Python means taking elements from one given index to another given index
2. We pass slice insted of index like this - [start_index:end_index]
3. We can also define the steps like this [Start_index: end_index: steps]
4. If we dont pass start_index its considered 0
5. If we dont pass the end_index its considered length of array in the dimension
6. If we dont pass the steps its considered 1

### There are two ways to access elements using slicing:
    1. Positive Indexing
    2. Negative Indexing

In [1]:
import numpy as np

In [2]:
my_array = np.array([1,2,3,4,5,6,7,8,9,10])
print(my_array[:])

[ 1  2  3  4  5  6  7  8  9 10]


In [3]:
print(my_array)

[ 1  2  3  4  5  6  7  8  9 10]


## 1. Postive Indexing

### 1. Start_Index

In [4]:
my_array = np.array([1,2,3,4,5,6,7,8,9,10])

print(my_array[2:])

[ 3  4  5  6  7  8  9 10]


### 2. End_Index

In [5]:
my_array = np.array([1,2,3,4,5,6,7,8,9,10])
print(my_array[:6])

[1 2 3 4 5 6]


### 3. Steps

In [6]:
my_array = np.array([1,2,3,4,5,6,7,8,9,10])

print(my_array[::2])

[1 3 5 7 9]


In [8]:
my_array = np.array([1,2,3,4,5,6,7,8,9,10])

print(my_array[::3])

[ 1  4  7 10]


## 2. Negative Slicing

In [9]:
my_array = np.array([1,2,3,4,5,6,7,8,9,10])

print(my_array[:-1])

[1 2 3 4 5 6 7 8 9]


In [10]:
my_array = np.array([1,2,3,4,5,6,7,8,9,10])

print(my_array[-1:])

[10]


### Steps

In [11]:
my_array = np.array([1,2,3,4,5,6,7,8,9,10])

print(my_array[:-1:2])

[1 3 5 7 9]


## Slicing 2-D Arrays

In [12]:
import numpy as np

In [13]:
my_array = np.array([[10,20,30,40,50],[60,70,80,90,100]])

In [14]:
my_array

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100]])

In [15]:
print(my_array.ndim)

2


In [16]:
print(my_array[1,])

[ 60  70  80  90 100]


In [17]:
print(my_array[1,2:])

[ 80  90 100]


In [18]:
print(my_array[1,::2])

[ 60  80 100]


In [19]:
print(my_array[:4, 2])

[30 80]


In [20]:
print(my_array[:2, 4])

[ 50 100]


In [22]:
print(my_array[0:2, 2:])

[[ 30  40  50]
 [ 80  90 100]]


### Data Types in Python

### By Default have these data types:
    1. String - used to represent text data, the text data under quote marks Example - "Python Developer"
    2. Integer - used to represent integer number - Example - 10 ,20, 30
    3. Float - used to represent real number Example - 12.12, 45.12
    4. Boolean - used to represent the True or False
    5. Complex - used to represent complex number Example - 1.0 + 2.0j

## Data Types in Numpy

1. Numpy has extra datatypes and refers to data types with one character like  i for integers, u for unassign integers etc.
2. Below list are the data types in Numpy and characters used  to represent data

1. i - Integer
2. b - boolean
3. u - unsigned integer
4. f - float
5. c - complex float
6. m - timedelta
7. M - datetime
8. O - object
9. S - String
10. U - unicode string
11. Fixed chunk of memory for other type(void)

In [23]:
import numpy as np

my_array = np.array([10,20,30,40])
print(my_array)

[10 20 30 40]


In [24]:
print(my_array.dtype)

int32


In [25]:
my_array = np.array(['Banana','Apple','Mango',"Cherry"])
print(my_array)

['Banana' 'Apple' 'Mango' 'Cherry']


In [26]:
print(my_array.dtype)

<U6


## Creating Arrays with Defined Data Types

In [27]:
my_array = np.array([10,20,30,40,50],dtype="S")
print(my_array)

print(my_array.dtype)

[b'10' b'20' b'30' b'40' b'50']
|S2


In [28]:
my_array = np.array([10,20,30,40,50],dtype="i")
print(my_array)

print(my_array.dtype)

[10 20 30 40 50]
int32


In [29]:
my_array = np.array([10,20,30,40,50],dtype="f")
print(my_array)

print(my_array.dtype)

[10. 20. 30. 40. 50.]
float32


In [31]:
my_array = np.array([10,20,30,40,50],dtype="U")
print(my_array)

print(my_array.dtype)

['10' '20' '30' '40' '50']
<U2


In [33]:
my_array = np.array([10,20,30,40,50],dtype="i8")
print(my_array)

print(my_array.dtype)

[10 20 30 40 50]
int64


In [34]:
my_array = np.array(['10','20','30','40','50'],dtype="S")
print(my_array)

print(my_array.dtype)

[b'10' b'20' b'30' b'40' b'50']
|S2


In [36]:
my_array = np.array(['10','20','30','40','50','a'],dtype="i")
print(my_array)

print(my_array.dtype)

ValueError: invalid literal for int() with base 10: 'a'