## Create a Numpy ndarray Object

1. Numpy used to work with array. The array object is in Numpy called as ndarray
2. We can create a Numpy **ndarray** object by using **array()** function
3. type() This is inbuilt function tell us use the type of the object passed to it.
4. To create an ndarray, we can pass list, tuple or any array-like object into array() method it will be converted into ndarray

In [1]:
import numpy as np

In [2]:
my_array = np.array([1,2,3,4,5,6])
print(my_array)
print(type(my_array))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [3]:
my_array = np.array((1,2,3,4,5,6))
print(my_array)
print(type(my_array))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


### Dimensions in Arrays

1. A dimension in Arrays is one level of array depth (nested array)
2. Nested Array are arrays that have arrays of their elements
3. There are different types of Arrays:
    1. 0-D Array
    2. 1-D Array
    3. 2-D Array
    4. 3-D Array

## 1. 0-D Arrays

1. 0-D Array or Scalers are the elements in the array each value in array is a 0-D Array

In [4]:
import numpy as np

my_array = np.array(40)
print(my_array)

40


In [7]:
print(type(my_array))
print(np.ndim(my_array))

<class 'numpy.ndarray'>
0


In [8]:
import numpy as np

my_array = np.array(1440)
print(my_array)

1440


In [9]:
print(type(my_array))
print(np.ndim(my_array))

<class 'numpy.ndarray'>
0


## 2. 1-D Arrays

1. An array that has 0-D array as its elements is called uni-dimensional or 1-D Array
2. These are most common array or Basic Arrays

In [10]:
import numpy as np

my_array = np.array([10,20,30,40,50,60])
print(my_array)

print(type(my_array))
print(np.ndim(my_array))

[10 20 30 40 50 60]
<class 'numpy.ndarray'>
1


## 3. 2-D Arrays

1. An array that has 1-D arrays as its elements is called 2-D array
2. These are used to represent matrix or 2nd order tensors
3. Numpy has a whole sub module dedicated towords matrix operations called numpy.mat

In [11]:
import numpy as np

my_array = np.array([[10,20,30],[40,50,60]])
print(my_array)


print(type(my_array))
print(np.ndim(my_array))

[[10 20 30]
 [40 50 60]]
<class 'numpy.ndarray'>
2


## 4. 3-D Arrays

1. An arrays that has 2-D arrays (matrix) as its elements is called as 3-D Array
2. These are used to represent 3rd order tensor 

In [14]:
import numpy as np

my_array = np.array([[[10,20,30],[40,50,60]],[[70,80,90],[100,110,120]]])
print(my_array)

print(type(my_array))
print(np.ndim(my_array))

[[[ 10  20  30]
  [ 40  50  60]]

 [[ 70  80  90]
  [100 110 120]]]
<class 'numpy.ndarray'>
3


## Check Number of Dimensions

In [15]:
my_array_1 = np.array(40)
my_array_2 = np.array([10,20,30,40,50,60])
my_array_3 = np.array([[10,20,30],[40,50,60]])
my_array_4 = np.array([[[10,20,30],[40,50,60]],[[70,80,90],[100,110,120]]])

print(np.ndim(my_array_1))
print(np.ndim(my_array_2))
print(np.ndim(my_array_3))
print(np.ndim(my_array_4))

0
1
2
3


## Higher Dimensional Arrays

1. An Arrays can have any number of dimensions
2. When the array is created you can define the number of dimensions by using ndmin arguments

In [16]:
my_array = np.array([10,20,30,40,50,60,70,80,90], ndmin = 5)

print(my_array)

print("Number of Dimensions: ", my_array.ndim)

[[[[[10 20 30 40 50 60 70 80 90]]]]]
Number of Dimensions:  5


In [17]:
my_array = np.array([10,20,30,40,50,60,70,80,90], ndmin = 4)

print(my_array)

print("Number of Dimensions: ", my_array.ndim)

[[[[10 20 30 40 50 60 70 80 90]]]]
Number of Dimensions:  4


In [19]:
my_array = np.array([10,20,30,40,50,60,70,80,90], ndmin = 6)

print(my_array)

print("Number of Dimensions: ", my_array.ndim)

[[[[[[10 20 30 40 50 60 70 80 90]]]]]]
Number of Dimensions:  6


# Access Array Elements

1. Array indexing is the same as accessing an array elements
2. You can access an array elements by referring to its index number
3. The index in Numpy arrays starts with 0, meaning that the first elements or arrray has index 0, second elements has index 1 etc
4. There are two ways to access Arrrays Elements:
    1. Positive Indexing
    2. Negative Indexing
    3. Range of Indexing (slicing)

## 1. Positive Indexing

## 1. 0-D Array

In [20]:
import numpy as np

my_array = np.array(5)
print(my_array)

5


In [21]:
print(my_array[0])

IndexError: too many indices for array: array is 0-dimensional, but 1 were indexed

## 2. 1-D Arrays

In [22]:
import numpy as np

my_array = np.array([10,20,30,40,50,60])
print(my_array)

[10 20 30 40 50 60]


In [23]:
my_array[2]

30

In [24]:
my_array[:4]

array([10, 20, 30, 40])

In [25]:
my_array[::2]

array([10, 30, 50])

## 3. 2-D Arrays

1. To access elements from 2-D arrays we can use comma separated integers representing the dimension and index of the elements
2. 2-D Arrays like a table with rows and column, where the dimension represent the ros and index represent the columnn 

In [26]:
import numpy as np

my_array = np.array([[10,20,30],[40,50,60]])
print(my_array)

[[10 20 30]
 [40 50 60]]


**print("Access first 1-d elements list from 2-D Array: ",my_array[dimesion,dimension_elements])**

In [28]:
print("Access first 1-d elements list from 2-D Array: ",my_array[0])
print("Access first 1-d elements list from 2-D Array: ",my_array[1])

Access first 1-d elements list from 2-D Array:  [10 20 30]
Access first 1-d elements list from 2-D Array:  [40 50 60]


In [29]:
print("Access first 1-d elements list from 2-D Array: ",my_array[0,2])
print("Access first 1-d elements list from 2-D Array: ",my_array[1,1])

Access first 1-d elements list from 2-D Array:  30
Access first 1-d elements list from 2-D Array:  50


In [30]:
print("Access first 1-d elements list from 2-D Array: ",my_array[0,:2])
print("Access first 1-d elements list from 2-D Array: ",my_array[1,1:])

Access first 1-d elements list from 2-D Array:  [10 20]
Access first 1-d elements list from 2-D Array:  [50 60]


## 4. 3-D Arrays

In [31]:
import numpy as np

my_array = np.array([[[10,20,30],[40,50,60]],[[70,80,90],[100,110,120]]])
print(my_array)

[[[ 10  20  30]
  [ 40  50  60]]

 [[ 70  80  90]
  [100 110 120]]]


In [32]:
print("Access first 1-d elements list from 3-D Array: ",my_array[0])
print("Access first 1-d elements list from 3-D Array: ",my_array[1])

Access first 1-d elements list from 3-D Array:  [[10 20 30]
 [40 50 60]]
Access first 1-d elements list from 3-D Array:  [[ 70  80  90]
 [100 110 120]]


In [35]:
print("Access first 1-d elements list from 3-D Array: ",my_array[0,0])
print("Access first 1-d elements list from 3-D Array: ",my_array[0,1])
print("Access first 1-d elements list from 3-D Array: ",my_array[1,0])
print("Access first 1-d elements list from 3-D Array: ",my_array[1,1])

Access first 1-d elements list from 3-D Array:  [10 20 30]
Access first 1-d elements list from 3-D Array:  [40 50 60]
Access first 1-d elements list from 3-D Array:  [70 80 90]
Access first 1-d elements list from 3-D Array:  [100 110 120]


In [36]:
print("Access first 1-d elements list from 3-D Array: ",my_array[0,0,2])
print("Access first 1-d elements list from 3-D Array: ",my_array[0,1,1])
print("Access first 1-d elements list from 3-D Array: ",my_array[1,0,0])
print("Access first 1-d elements list from 3-D Array: ",my_array[1,1,1])

Access first 1-d elements list from 3-D Array:  30
Access first 1-d elements list from 3-D Array:  50
Access first 1-d elements list from 3-D Array:  70
Access first 1-d elements list from 3-D Array:  110


In [37]:
print("Access first 1-d elements list from 3-D Array: ",my_array[0,0,1:])
print("Access first 1-d elements list from 3-D Array: ",my_array[0,1,:2])
print("Access first 1-d elements list from 3-D Array: ",my_array[1,0,:])
print("Access first 1-d elements list from 3-D Array: ",my_array[1,1,:1])

Access first 1-d elements list from 3-D Array:  [20 30]
Access first 1-d elements list from 3-D Array:  [40 50]
Access first 1-d elements list from 3-D Array:  [70 80 90]
Access first 1-d elements list from 3-D Array:  [100]


## Negative Indexing

## 1. 0-D Elements

In [38]:
import numpy as np

my_array = np.array(5)
print(my_array)

5


## 2. 1-D Arrays