# Why Do we need to Perform Feature Scalling ?

## What is Feature Scalling ? 

1. Feature scalling is a technique to standardize independent variable present in the data in fixed range.
2. It is performed during data-preprocessing to handle higly varing mangnitudes or values or units
3. If feature scalling is not done, the machine learning trends to weight greater values, higher and consider smaller values as the lower values, regardless of the unit of the values.

## Why Scalling ?

1. Most of the times, your dataset will contain features highly variying in magnitudes, units and range.
2. But Since, Machine learning algorithm use Ecludian Distance between two data points (variable) in there computation this is a problem

### Example:

### Let's consider an example of House Price Prediction

1. It willl have many features like No.Of Bedroom, No Square Feet Area, BHK etc.
2. As you can guess the no. of Bedrooms will variying between 1 to 5, but No of Square feet area will range 500 to 2000
2. Huge difference between in the range of both feature

### 1. There are several ways to handle feature scalling. There are 5 most common feature scalling techniques

1. Absoulte Maximum Scalling
2. Min Max Scalling
3. Normalization
4. Standardization
5. Robust Scalling

### 1. Absolute Maximum Scalling

1. Find the Absolute value of the feature in datasets
2. Devide all the values in the by that maximum values
3. If we do this all for the numerical variables[column], then all values between -1 to 1

#### This Method of scalling required two steps

1. We should first select the maximum absolute value out of all the entries of perticular measure
2. Then after this, We devide each entry of the column by this maximum value

**Forumula - X_scaled = X_[i] - max(|X|) / max(|X|)**

In [1]:
data = {
    'LotArea':[8450,9600,11250,9550,14623],
    'SubClass':[60,20,60,70,60]
}

In [2]:
import pandas as pd

In [3]:
df = pd.DataFrame(data)

In [4]:
df

LotArea  SubClass
0     8450        60
1     9600        20
2    11250        60
3     9550        70
4    14623        60

In [5]:
df = df.to_csv('absoulute_scalling.csv')

In [6]:
df = pd.read_csv('absoulute_scalling.csv')

In [7]:
df.head()

Unnamed: 0  LotArea  SubClass
0           0     8450        60
1           1     9600        20
2           2    11250        60
3           3     9550        70
4           4    14623        60

In [8]:
df = df.drop('Unnamed: 0', axis=1)

In [9]:
df.head()

LotArea  SubClass
0     8450        60
1     9600        20
2    11250        60
3     9550        70
4    14623        60

In [10]:
import numpy as np

In [11]:
max_values = np.max(np.abs(df))

In [12]:
max_values

14623

In [13]:
print((df - max_values) / max_values)

    LotArea  SubClass
0 -0.422143 -0.995897
1 -0.343500 -0.998632
2 -0.230664 -0.995897
3 -0.346919 -0.995213
4  0.000000 -0.995897


## Disadvantages of Absolute Feature Scalling

1. Techniques is to sensitive to outliers, Like consider the feature of House Price Prediction [square_feet]
2. If 99% of the house square_feet area of less than 1000, and even if just one House has a square_feet_area of 20000, then all those values will be scalled down to less than 0.5

1. using [sin()] and [cos()] function will be used and will see range how feature scalling technique affect there is mangnitude sin() will be ranging between -1 to 1 and 50 *cos() will be ranging between -50 to 50

In [14]:
x = np.arange(0,20,0.4)

In [15]:
x

array([ 0. ,  0.4,  0.8,  1.2,  1.6,  2. ,  2.4,  2.8,  3.2,  3.6,  4. ,
        4.4,  4.8,  5.2,  5.6,  6. ,  6.4,  6.8,  7.2,  7.6,  8. ,  8.4,
        8.8,  9.2,  9.6, 10. , 10.4, 10.8, 11.2, 11.6, 12. , 12.4, 12.8,
       13.2, 13.6, 14. , 14.4, 14.8, 15.2, 15.6, 16. , 16.4, 16.8, 17.2,
       17.6, 18. , 18.4, 18.8, 19.2, 19.6])

In [16]:
y1 = np.sin(x)

In [17]:
y1

array([ 0.        ,  0.38941834,  0.71735609,  0.93203909,  0.9995736 ,
        0.90929743,  0.67546318,  0.33498815, -0.05837414, -0.44252044,
       -0.7568025 , -0.95160207, -0.99616461, -0.88345466, -0.63126664,
       -0.2794155 ,  0.1165492 ,  0.49411335,  0.79366786,  0.96791967,
        0.98935825,  0.85459891,  0.58491719,  0.22288991, -0.17432678,
       -0.54402111, -0.82782647, -0.98093623, -0.97917773, -0.82282859,
       -0.53657292, -0.16560418,  0.23150983,  0.59207351,  0.85916181,
        0.99060736,  0.96565778,  0.78825207,  0.48639869,  0.10775365,
       -0.28790332, -0.63810668, -0.88756703, -0.99690007, -0.9488445 ,
       -0.75098725, -0.43456562, -0.04953564,  0.34331493,  0.68196362])

In [18]:
y2 = np.cos(x)

In [19]:
y2

array([ 1.        ,  0.92106099,  0.69670671,  0.36235775, -0.02919952,
       -0.41614684, -0.73739372, -0.94222234, -0.99829478, -0.89675842,
       -0.65364362, -0.30733287,  0.08749898,  0.46851667,  0.77556588,
        0.96017029,  0.99318492,  0.86939749,  0.60835131,  0.25125984,
       -0.14550003, -0.51928865, -0.81109301, -0.97484362, -0.98468786,
       -0.83907153, -0.56098426, -0.19432991,  0.20300486,  0.56828963,
        0.84385396,  0.9861923 ,  0.97283257,  0.80588396,  0.51170399,
        0.13673722, -0.25981736, -0.61535248, -0.87373698, -0.99417763,
       -0.95765948, -0.76994796, -0.46067859, -0.07867819,  0.31574375,
        0.66031671,  0.90064017,  0.99877236,  0.93922035,  0.7313861 ])

In [20]:
y2 = np.cos(x) * 50

In [21]:
y2

array([ 50.        ,  46.0530497 ,  34.83533547,  18.11788772,
        -1.45997612, -20.80734183, -36.86968578, -47.11111703,
       -49.91473879, -44.83792082, -32.68218104, -15.3666435 ,
         4.37494917,  23.42583357,  38.77829393,  48.00851433,
        49.65924594,  43.46987452,  30.41756573,  12.56299213,
        -7.27500169, -25.96443271, -40.5546507 , -48.74218107,
       -49.23439279, -41.95357645, -28.04921287,  -9.71649532,
        10.15024319,  28.41448149,  42.19269794,  49.30961511,
        48.64162828,  40.29419788,  25.58519962,   6.83686091,
       -12.99086781, -30.76762415, -43.68684915, -49.70888126,
       -47.88297402, -38.49739803, -23.03392937,  -3.93390974,
        15.78718775,  33.01583541,  45.03200862,  49.93861783,
        46.96101733,  36.56930478])

In [22]:
y1_new = y1 / max(y1)

In [23]:
y2_new = y2/ max(y2)

In [24]:
y1_new

array([ 0.        ,  0.38958446,  0.7176621 ,  0.93243667,  1.        ,
        0.90968531,  0.67575132,  0.33513105, -0.05839904, -0.44270921,
       -0.75712533, -0.95200801, -0.99658955, -0.88383152, -0.63153592,
       -0.27953469,  0.11659892,  0.49432413,  0.79400643,  0.96833257,
        0.98978029,  0.85496346,  0.58516671,  0.22298499, -0.17440115,
       -0.54425318, -0.8281796 , -0.98135468, -0.97959543, -0.8231796 ,
       -0.53680181, -0.16567482,  0.23160858,  0.59232608,  0.85952832,
        0.99102993,  0.96606971,  0.78858832,  0.48660618,  0.10779962,
       -0.28802613, -0.63837889, -0.88794565, -0.99732532, -0.94924925,
       -0.7513076 , -0.434751  , -0.04955677,  0.34346138,  0.68225453])

In [25]:
y2_new

array([ 1.        ,  0.92106099,  0.69670671,  0.36235775, -0.02919952,
       -0.41614684, -0.73739372, -0.94222234, -0.99829478, -0.89675842,
       -0.65364362, -0.30733287,  0.08749898,  0.46851667,  0.77556588,
        0.96017029,  0.99318492,  0.86939749,  0.60835131,  0.25125984,
       -0.14550003, -0.51928865, -0.81109301, -0.97484362, -0.98468786,
       -0.83907153, -0.56098426, -0.19432991,  0.20300486,  0.56828963,
        0.84385396,  0.9861923 ,  0.97283257,  0.80588396,  0.51170399,
        0.13673722, -0.25981736, -0.61535248, -0.87373698, -0.99417763,
       -0.95765948, -0.76994796, -0.46067859, -0.07867819,  0.31574375,
        0.66031671,  0.90064017,  0.99877236,  0.93922035,  0.7313861 ])

## 2. Min-Max Scalling

1. This method of scalling requres two steps:
    1. First, We are find the minimum value of our column
    2. The we will substract the minimum value from the entry  and devide the result by the difference between the maximum and minimum value

![](https://substackcdn.com/image/fetch/f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F742f0335-cc0f-46d6-84a7-f531c8f5aff5_547x140.png)

In [26]:
from sklearn.preprocessing import MinMaxScaler

In [27]:
scaler = MinMaxScaler()

In [28]:
# help(scaler)

In [29]:
scaled_data = scaler.fit_transform(df)


In [30]:
scaled_data

array([[0.        , 0.8       ],
       [0.18629516, 0.        ],
       [0.45358821, 0.8       ],
       [0.17819537, 1.        ],
       [1.        , 0.8       ]])

In [31]:
scaled_df = pd.DataFrame(scaled_data, columns=df.columns)

In [32]:
scaled_df

LotArea  SubClass
0  0.000000       0.8
1  0.186295       0.0
2  0.453588       0.8
3  0.178195       1.0
4  1.000000       0.8

### 3. Normalization

1. The method is more or less the same as the min-max method but insted of the minimum value
2. We substract each entry by the mean value of whole data and then devide the result by the difference between the minimum and the maximum value

In [33]:
from sklearn.preprocessing import Normalizer

In [34]:
scaler = Normalizer()

In [36]:
# help(scaler)

In [37]:
scaled_data = scaler.fit_transform(df)
scaled_df = pd.DataFrame(scaled_data,columns=df.columns)

In [38]:
scaled_df.head()

LotArea  SubClass
0  0.999975  0.007100
1  0.999998  0.002083
2  0.999986  0.005333
3  0.999973  0.007330
4  0.999992  0.004103

![](https://www.researchgate.net/publication/370281792/figure/fig1/AS:11431281153784125@1682531264234/Data-normalization-formula.png)

## 4. Standardization

1. We calculate the z-score value for each data points and replace those value with standardize value
2. This method of scalling is basically based on central tendancies and variance of the data
3. First, we should calculate the mean and standard deviation of the data we would like to normalize
4. Then we are substract the mean value from each entry and then devide the result by the standard deviation

**X[new] = X - Xmean / standard deviation**

![](https://miro.medium.com/v2/resize:fit:399/1*cvrpJ9lx24D1AuXNpWskZA.jpeg)

In [39]:
from sklearn.preprocessing import StandardScaler

In [40]:
scaler = StandardScaler()

In [41]:
scaled_data = scaler.fit_transform(df)
scaled_df = pd.DataFrame(scaled_data, columns=df.columns)

In [42]:
scaled_df.head()

LotArea  SubClass
0 -1.040075  0.344124
1 -0.507202 -1.950034
2  0.257354  0.344124
3 -0.530370  0.917663
4  1.820293  0.344124

**Note: Make sure that all the features are centered around the mean value with standard deviation value of 1**

### 5. Robust Scalling

1. In Robust scalling method we use two main statistical measure of the data:
    1. Median
    2. Inter-Quartile Range

1. After calculating these two values we are supposed to substract the median from each entry and then devide by the result of IQR

**X[new] = X - Xmedian / IQR**

In [43]:
df = pd.read_csv('absoulute_scalling.csv')

In [44]:
df.head()

Unnamed: 0  LotArea  SubClass
0           0     8450        60
1           1     9600        20
2           2    11250        60
3           3     9550        70
4           4    14623        60

In [45]:
df = df.drop('Unnamed: 0', axis=1)

In [46]:
df.head()

LotArea  SubClass
0     8450        60
1     9600        20
2    11250        60
3     9550        70
4    14623        60

In [49]:
np.sort(df['LotArea'])

array([ 8450,  9550,  9600, 11250, 14623], dtype=int64)

In [50]:
np.sort(df['SubClass'])

array([20, 60, 60, 60, 70], dtype=int64)

In [51]:
Median_value = [9600,60]

In [52]:
from sklearn.preprocessing import RobustScaler

In [53]:
scaler = RobustScaler()

In [54]:
scaled_data = scaler.fit_transform(df)
scaled_df = pd.DataFrame(scaled_data, columns=df.columns)

In [55]:
scaled_df.head()

LotArea  SubClass
0 -0.676471       0.0
1  0.000000     -40.0
2  0.970588       0.0
3 -0.029412      10.0
4  2.954706       0.0

## InterQuartile Range 

InterQuartile Range is related to the quartile concept which comes under the parent topic

![](https://www.bachelorprint.com/wp-content/uploads/2023/07/Interquartile-range-Definition.jpg)

![](https://upload.wikimedia.org/wikipedia/commons/1/1a/Boxplot_vs_PDF.svg)

![](https://www.scribbr.com/wp-content/uploads/2022/01/interquartile-range.png)

1. The Interqurtile range can be defined as the distance between the Upper Quartile and the Lower Quartile
2. It is also called as Mid Spread.
3. A Quartile is used to partition the given data into four parts by three cuts:
    1. Quartile 1:
        1. It is also called as the **Lower Quartile** which cuts the first half of sorted data
    2. Quartile 2:
        2. It is a **Median** value which is the center value in sorted data
    3. Quartile 3:
        3. It is also called as **Upper Quartile** that the last of of the ordered data

#### InterQuartile Range Formula

1. InterQuartile Range formula is the difference between the Third/UpperQurtile and First/LowerQuartile
2. It is calculation of variation while deviding the dataset into Quartile

**IQR = Q3 - Q1**

1. Q3 - Upper Quartile
2. Q1 - Lower Quartile

Upper Quartile is calculated using the Formula

**Q3 = ((3 * (n + 1))/4)the term**

where n is the number of terms

**Q1 = (((n + 1))/4)the term**

### Steps to Perform IQR

1. Step_1 - Sort the data in ascending order
2. Step_2 - Find Upper Quartile and Lower Quartile for the given dataset
3. Step_3 - Find Inter Quartile Range

## Question - Find the InterQuartile Range for the given data 20,10,50,40,25,70,30

### Step_1 - Given data is unsorted manner so first need to sort in ascending order

In [56]:
lst = [20,10,50,40,25,70,30]

In [58]:
sorted_lst = np.sort(lst)

In [60]:
print(sorted_lst)

[10 20 25 30 40 50 70]


### Step_2 - Find the Quartile

### Find the Upper/Third Quartile

### Step_3 - Find IQR (Inter Quartile Range)